packages:
    - 'apps/*'
    - 'packages/*'
nodeLinker: hoisted
blockExoticSubdeps: false
overrides:
    '@electron/node-gyp': 'https://codeload.github.com/electron/node-gyp/tar.gz/06b29aafb7708acef8b3669835c8a7857ebc92d2'
allowBuilds:
    electron: true
    electron-winstaller: true
    esbuild: true
    sharp: true
